### ISSUE TITLE
Deezer is not starting up with mopidy 2.0.0

### ISSUE THREAD

**Issue by Montaldo** [rusty-dev/mopidy-deezer#2]
Are you still maintaining this plugin?

**Comment by rusty-dev** [comment]
what exactly is the problem, what OS are u using? Running fine for me with mopidy 2.0.0 on Ubuntu 14 and Raspbian 8.

**Comment by Montaldo** [comment]
I am running 2.0.0 on Raspbian Jesse 4.1

I do see that its doing something in the logs when I search for all services.
mopidy[7203]: INFO     Searching for images for uris: [u'deezer:track:2307486']

You cannot search with Deezer as a service because it is not listed. 

Is there also a possibility to login on deezer with this plugin?

**Comment by rusty-dev** [comment]
@Montaldo no login functionality yet, as for isolation search - I'll look into it.

**Comment by Montaldo** [comment]
Awesome. Great work!

**Comment by rusty-dev** [comment]
Doesn't seem like there's a problem with my code that causes it not to show Deezer search. I've looked multiple times comparing it to mopidy-youtube (which does show up as a separate search option) and I didn't find any issues. This could possibly be a bug with mopidy, because for plugin to have a separate search option, it needs to have a [library provider](http://mopidy.readthedocs.org/en/latest/api/backend/#mopidy.backend.LibraryProvider) with search() function and I have that.
A normal search (through all services) should work however, or are you trying difficulties on making that work as well? Try [Mopidy-MusicBox-Webclient](https://pypi.python.org/pypi/Mopidy-MusicBox-Webclient/2.0.0).
