### ISSUE TITLE
Deezer API

### ISSUE THREAD

**Issue by jjok** [rusty-dev/mopidy-deezer#4]
Hey. I was just wondering why you're imitating the browser, rather than using the Deezer API?

Did you look into using the API and decide not to?

**Comment by rusty-dev** [comment]
Yes, I've seen Deezer API, it is limited by amount of requests per unit of time and doesn't support playback.

**Comment by markbaas** [comment]
Emulating the browser is a fine approach, I wonder how it is so easy to get to the streaming api without a user login. Where did you get the tokens at line 283 and 308 in deezer.py from? Are you sure those are not related to some user account?

**Comment by rusty-dev** [comment]
@markbaas I was surprised myself how they kept everything "open", here's the point where I get the [temporary user token](https://github.com/rusty-dev/mopidy-deezer/blob/master/mopidy_deezer/deezer.py#L96-L98). This is basically the API token that would be given to a user, but, they generate it even without logging in, just opening "www.deezer.com" is enough to get the token (pretty poor coding if u ask me). The rest of streaming API comes directly from their flash player app, again, instead of only sending music to authorized users, they just store every track in a predefined link and that link is generated and decrypted client-side. If they actually wanted to close this down (and, since they haven't exposed this API officially, I think they do), Deezer developers could do so in a blink of an eye by adding a layer of authorization between a track link and the actual track data... So this is basically the reason why I don't care much about developing this plugin further. This was basically a weekend project to allow us to listen to music from Deezer in office through rhaspbery+mopidy server.

**Comment by markbaas** [comment]
Yea this looks like a major security leak as we're able to access deezer without an account. How were you able to disassemble the flash player? Sorry for asking so many questions, but I just want to go through the same steps as you did :)

Even if they add an authorization layer, this could be updated using the authentication token probably.

**Comment by rusty-dev** [comment]
@markbaas yes, it would still be accessible through authentication token, but only with that user's rights, meaning non-premium accounts can't get premium tracks and so on. Honestly, I don't get why they didn't do so in the first place and also allow track access in their public API as a result.

as for disassembling, I used some web-service that I found by googling, don't remember which one. In any case, flash plugin code is an absolute pain to read, not to mention there are actually two flash files in one flash plugin. The underlying one is also in ActionScript 2 and is used for encryption, it transfers information from one flash script to another in a very weird way too, the top plugins draws pixels on the bottom plugin's canvas, and the bottom plugin later translates those pixels back into data, then back again... [Don't even ask.](http://i2.kym-cdn.com/entries/icons/original/000/006/482/template.jpg)

**Comment by markbaas** [comment]
Yea, for a company that has to protect the music rights, this would be a serious problem. If the sony and universal lawyers hear about this, they'll be in serious problems. They should just have exposed their html5 and streaming api... seems that flash isn't really doing anything for them.

**Comment by rusty-dev** [comment]
@markbaas I don't think this is such a huge problem. If you are able to listen to a song - that means you have downloaded it, getting to the source track is easy and they know it. People that want to download songs from Deezer will still be able to do so even if they fix this particular issue. Same goes for iTunes, Spotify, Google Play and pretty much everything else. Protecting music rights isn't about being able to download a song from a service, but rather about the service not providing such a **feature**.  Nothing can be done to prevent this from happening really.
That being said, I don't think Deezer developers care too much about it for this very reason. In any case, giving a temporary token that grants access to EVERYTHING without even logging in - not good...

**Comment by markbaas** [comment]
Yea it's probably a bug in their system, the login token should be provided when logged in.

**Comment by rusty-dev** [comment]
I mean, it's still a small bug compared to songs of any quality being accessible from a non-privileged token.

**Comment by markbaas** [comment]
Let's see if they figure out... Their software is quite crappy, the flow doesn't know anything about music preferences, their windows phone app is very buggy, etc... so I don't see much developer effort in general.

**Comment by jjok** [comment]
I've done a bit on #3. All I've had to do it work out my user ID, then I can use that to list my favourite artists, albums, and my playlists. Have a look here, if you like efa0219
